# -*- coding: utf-8 -*-
"""Agente.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13qIZdJzkR3kwhoi4Ku71-dtQekV5a_xI
"""



import streamlit as st
import google.generativeai as genai
from PIL import Image
import io

# ------------------------------
# CONFIG DE GOOGLE API KEY
# ------------------------------
genai.configure(api_key="AIzaSyAbzZHK_i2U0u0CwEmpLqTndGXcc6TKbYE")

#genai.configure(api_key=st.secrets["AIzaSyAvceZtL7I0ZEwurKtDkePN2Dj77xcDfZ4"])

# ------------------------------
# MODELO
# ------------------------------
model = genai.GenerativeModel(model_name="models/gemini-2.5-flash")

# ------------------------------
# INTERFAZ
# ------------------------------
st.set_page_config(page_title="Nutri-Asistente IA", layout="centered")
st.title("🧠 Nutri-Asistente Multimodal IA")
st.write("Sube tu estudio clínico + platillo y obtén un análisis personalizado.")

# Para simular conversación tipo ChatGPT
if "messages" not in st.session_state:
    st.session_state.messages = []

# Mostrar historial de mensajes
for msg in st.session_state.messages:
    with st.chat_message(msg["role"]):
        st.write(msg["content"])

# ----------------------------------------
# PRIMER MENSAJE DEL ASISTENTE
# ----------------------------------------
if len(st.session_state.messages) == 0:
    st.session_state.messages.append({
        "role": "assistant",
        "content": "👋 Hola, soy tu asistente de salud y nutrición. Para comenzar:\n1) ¿Cuál es tu edad?\n2) ¿Tienes antecedentes como diabetes, hipertensión o colesterol alto?"
    })
    with st.chat_message("assistant"):
        st.write(st.session_state.messages[-1]["content"])

# ----------------------------------------
# INPUT DEL USUARIO
# ----------------------------------------
user_input = st.chat_input("Escribe tu respuesta...")

if user_input:
    # Guardar mensaje
    st.session_state.messages.append({"role": "user", "content": user_input})
    with st.chat_message("user"):
        st.write(user_input)


# ----------------------------------------------------------
# PASO 1: EL ASISTENTE PIDE LA IMAGEN DEL ESTUDIO CLÍNICO
# ----------------------------------------------------------
if "info_ok" not in st.session_state and len(st.session_state.messages) >= 2:
    st.session_state.info_ok = True
    with st.chat_message("assistant"):
        st.write("Perfecto. Ahora por favor **sube la imagen de tu estudio clínico (foto o PDF en imagen).**")

# Subida de estudio clínico
image1 = st.file_uploader("Sube tu estudio clínico", type=["jpg", "jpeg", "png"], key="study_uploader")

if image1 and "study_uploaded" not in st.session_state:
    st.session_state.study_uploaded = True
    st.session_state.image1_bytes = image1.read()
    st.session_state.messages.append({"role": "assistant", "content": "Gracias. Ahora sube la **imagen del platillo** que deseas analizar."})
    with st.chat_message("assistant"):
        st.write("Gracias. Ahora sube la **imagen del platillo** que deseas analizar.")

# ----------------------------------------------------------
# PASO 2: EL ASISTENTE PIDE LA IMAGEN DEL PLATILLO
# ----------------------------------------------------------
image2 = None
if "study_uploaded" in st.session_state:
    image2 = st.file_uploader("Sube tu platillo", type=["jpg", "jpeg", "png"], key="food_uploader")

# ----------------------------------------------------------
# PASO 3: LLAMADA AL MODELO
# ----------------------------------------------------------
if image2 and "done" not in st.session_state:
    st.session_state.done = True
    image2_bytes = image2.read()

    # Tu prompt EXACTO
    prompt = """
SISTEMA:
Eres un asistente multimodal experto en salud y nutrición. Cuando recibas: (A) imagen de estudios clínicos de sangre y/o historial clínico en texto que no es obligatorio subir preguntar si se subira y (B) imagen de un platillo, debes:

1) Analizar cada entrada por separado y en conjunto.
2) Invocar internamente a varios "expertos" especializados (Nutrición, Cardiología, Endocrinología, Medicina Interna, y un Calculador de Porciones) que emitan su análisis independiente y una conclusión breve con una puntuación de confianza (0-100).
3) Aplicar un paso de SELF-CONSISTENCY: pedir a cada experto que reconsidere su respuesta 3 veces con pequeñas variaciones en el razonamiento; agregar una votación/consenso entre las respuestas y calcular la conclusión final y el intervalo de confianza.
4) Producir una respuesta final clara, accionable y estructurada para el usuario final, con:
   - Diagnóstico/observaciones clave del estudio clínico (A)
   - Identificación del platillo y estimación de porciones/calorías (B)
   - Breve descripción nutricional (macros principales)
   - Recomendación personalizada basada en el historial clínico (riesgo de diabetes, lípidos, hipertensión, etc.)
   - Cambios sugeridos al platillo (qué aumentar/reducir y por qué)
   - Riesgos o contraindicaciones urgentes (si aplica) y señalamiento de cuándo consultar a un profesional en persona
   - Puntuación de confianza global y desglose por experto
   - Si falta información crítica, una lista de preguntas concretas para obtenerla

RESTRICCIONES:
- No asumas diagnósticos definitivos; usa lenguaje de probabilidad.
- Si el contenido indica peligro inmediato, indica “Buscar atención médica urgente”.
- Referencias solo si se piden.


USUARIO:
(A) Imagen del estudio clínico: {imagen_estudio}
(B) Imagen del platillo: {imagen_platillo}

TAREAS:
1. Resumen rápido.
2. Hallazgos clave.
3. Identificación del platillo + porción + calorías + cantidad de fibra.
4. Recomendación dietética personalizada (tomar en cuenta IMC, tambien cantidades recomendadas).
5. Cambios sugeridos al platillo.
6. Puntuaciones por experto y analisis por experto.
7. Conclusión final + preguntas pendientes.

ENTREGABLE:
Responde únicamente con un texto claro y estructurado para el usuario. 
NO incluyas JSON, NO incluyas formato de datos, NO incluyas listas tipo JSON.
Solo texto natural en lenguaje humano, bien explicado y organizado.


DISCLAIMER: No sustituye una consulta médica.
"""

    with st.chat_message("assistant"):
        st.write("🧠 Analizando tus imágenes, por favor espera...")

    # Llamada al modelo
    response = model.generate_content(
        [
            prompt,
            {"mime_type": "image/jpeg", "data": st.session_state.image1_bytes},
            {"mime_type": "image/jpeg", "data": image2_bytes}
        ]
    )

    # Mostrar respuesta final tipo chat
    with st.chat_message("assistant"):
        st.write(response.text)

    st.session_state.messages.append({"role": "assistant", "content": response.text})
